CentralBank/urls.py
from django.contrib import admin
from django.urls import include, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name = "home"),
    re_path(r'^accounts/', include("accounts.urls")),
    re_path(r'^profile/', include("profiles.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Trybe Bank"
admin.site.site_title = "Trybe Bank Administration"
admin.site.index_title = "Bem-vindo à página de Administrador do Trybe Bank"

accounts/urls.py
from django.urls import include, re_path
from . import views

app_name = "accounts"

urlpatterns = [
    re_path("register/", views.register, name = "signup"),
    re_path("login/", views.sign_in, name = "signin"),
    re_path("logout/", views.logout_view, name = "logout"),
]

profiles/urls.py
from django.urls import re_path, path
from . import views
from profiles.views import TransactionsListView

app_name = "profiles"

urlpatterns = [
    re_path("account_status/", views.index, name = "account_status"),
    re_path("money_transfer/", views.money_transfer, name = "money_transfer"),
    re_path("view_transactions/", TransactionsListView.as_view(), name = "view_transactions"),
]

accounts/models.py
from django.db import models

profiles/models.py
from django.db import models

class Accounts (models.Model):
    account_number = models.IntegerField()
    balance = models.IntegerField(default=100)
    user_name = models.CharField(max_length = 150, default = None)
    
    def __str__(self):
         return str(self.account_number)

class Transactions(models.Model):
    debited_account_id = models.IntegerField()
    credited_account_id = models.IntegerField()
    value = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
         return str(self.created_at)
    

profiles/forms.py
from django import forms
from . import models

class TransactionsForm (forms.ModelForm):
    class Meta:
        model = models.Transactions
        fields = [
            "debited_account_id",
            "credited_account_id", 
            "value",
        ]

CentralBank/views.py
from django.shortcuts import render

def index(request):
    return render(request, "index.html")

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login
from django.contrib.auth import logout

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:signin")
        else:
            return redirect("accounts/sign_in.html")
    else:
        form = UserCreationForm()
    return render(request, "accounts/create_account.html", {"form": form})

def sign_in(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("profiles:account_status")
        else:
            return redirect("accounts/sign_in.html")
    else:
        form = AuthenticationForm()
        return render(request, "accounts/sign_in.html", {"form": form})

def logout_view(request):
    logout(request)
    return redirect("accounts:signin")

profiles/views.py
from django.shortcuts import render, redirect
from . import forms
from . import models
from profiles.models import Accounts 
from django.db.models import Q
from django_tables2 import SingleTableView
from .tables import TransactionsTable
import random

def randomGen():
    return int(random.uniform(100000, 999999))

def index(request):
    try:
        curr_user = Accounts.objects.get(user_name=request.user)
    except:
        curr_user = Accounts()
        curr_user.account_number = randomGen() 
        curr_user.balance = 100
        curr_user.user_name = request.user
        curr_user.save()
    return render(request, "profiles/profile.html", {"curr_user": curr_user})

def money_transfer(request):
    if request.method == "POST":
        form = forms.TransactionsForm(request.POST)
        if form.is_valid():
            curr_user = models.Accounts.objects.get(account_number=form['debited_account_id'].value())
            dest_user = models.Accounts.objects.get(account_number=form['credited_account_id'].value())
            transfer_amount = int(form['value'].value()) 
            if (curr_user.balance >= transfer_amount) and (curr_user != dest_user): 
                form.save()
                curr_user.balance = curr_user.balance - transfer_amount
                dest_user.balance = dest_user.balance + transfer_amount
                curr_user.save()
                dest_user.save()
        return redirect("profiles/profile.html")
    else:
        form = forms.TransactionsForm()
    return render(request, "profiles/money_transfer.html", {"form": form})

class TransactionsListView(SingleTableView):
    model = models.Transactions
    table_class = TransactionsTable
    template_name = 'profiles/view_transactions.html'
    
    def get_queryset(self):
            curr_user = Accounts.objects.get(user_name=self.request.user)
            conta = curr_user.account_number        
            return super().get_queryset().filter(Q(debited_account_id=conta) | Q(credited_account_id=conta))
    

accounts/templates/accounts/create_account.html
{% extends 'base_layout.html' %}
  
{% block bodycontent %}        
    <h2 class="container text-center" style="margin-top: 60px;">Criar nova conta</h2>
    <h6 class="text-center"><em>(Todos os campos são obrigatórios)</em></h6>
    <form class="container" action="/accounts/register/" method="post">
        {% csrf_token %}
        <section class="form-control">
            <h4>Preencha os seus dados</h4>
            {{ form }}
        </section>
        <input type="submit" class="form-control btn btn-danger" value="Criar conta" name="submit"/>
    </form>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".active").removeClass("active");
        $("#nav-create").addClass("active");

        $(".helptext").html("");

        var input_text = $("input[type=text]");
        input_text.addClass("form-control");

        var input_pass = $("input[type=password]");
        input_pass.addClass("form-control");

        $("form ul li").addClass("btn btn-danger");
    </script>
{% endblock %}

accounts/templates/accounts/sign_in.html
{% extends 'base_layout.html' %}
{% block bodycontent%}
    <div class="container bg-info" style="margin-top: 60px;"> 
        <form class="form-control" action="/accounts/login/" method="post">
            {% csrf_token %}
            <h2>Preencha os campos abaixo para fazer login</h2>
            {{ form }}
            <button type="submit" class="btn btn-success" style="margin-top: 10px; margin-bottom: 10px;">
                <i class="fa fa-sign-in"></i>
                Login
            </button>
            <small class="row">
                <a href="#" class="col text-left">Esqueceu a sua senha?</a>
                <a href="{% url 'accounts:signup' %}" class="col text-right">Criar nova conta</a>
            </small>
        </form>
    </div>
{% endblock %}
{% block scriptcontent %}
    <script>
        $(".active").removeClass("active");
        $("#nav-login").addClass("active");
        $("input").addClass("form-control");
    </script>
{% endblock %}

profiles/templates/profiles/money_transfer.html
{% extends 'profiles/profile_base_layout.html' %}
{% block bodycontent %}
    <section id="welcome_post" class="col-9" style="margin-top: 60px;">
        <h2>Bem-vindo, <span id="prof_name">{{ user }}.</span> </h2> 
        <form action="{ url 'profiles:money_transfer' }" method="post">
            {% csrf_token %}
            <h3 style="font-weight: 300;">
                {{ form }}
            </h3>
            <button type="submit" class="btn btn-danger">Transferir dinheiro</button>
        </form>
    </section>
{% endblock %}
{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#transfer").addClass("current");

        $("input").addClass("form-control");
        $("label").prepend("<br>")
    </script>
{% endblock %}

profiles/templates/profiles/profile.html
{% extends 'profiles/profile_base_layout.html' %}

{% block bodycontent %}

    <section id="welcome_post" class="col-9" style="margin-top: 60px;">
        <h2>Bem-vindo, <span id="prof_name">{{ user }}.</span> </h2>
        <h4 style="font-weight: 300;">É bom ter você por aqui.</h4>   
        <div class="text-center curr_bal"> 
            <h4>NÚMERO DA CONTA</h4> 
            <h1 id="curr_bal" class="btn-success">{{ curr_user.account_number }}</h1>
        </div>
        <div class="text-center curr_bal"> 
            <h4>SALDO ATUAL</h4> 
            <h1 id="curr_bal" class="btn-danger">R${{ curr_user.balance }}</h1> 
        </div>
    </section>

{% endblock %}

profiles/templates/profiles/profile_base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Trybe Bank | Perfil</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="{% static 'sort.js' %}"></script> 
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-success">
            <img src="/static/images/logo-negative-green.svg" width="50px">
            <a class="navbar-brand" href="index.html">Trybe Bank</a>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                    <a class="nav-item nav-link" href="/profile/account_status/">Profile<a>
                    <a class="nav-item nav-link" href="/admin">Admin<a>
                </div>
            </div>
        </nav>
        <div class="container-fluid row">
            <section id="side_panel" class="col-3 bg-dark" style="margin-top: 60px;">
                <img src="/static/images/logo-negative-green.svg" class="container btn">
                <a href="{% url 'profiles:account_status' %}" class="current side" id="status">Status da conta</a> <br> <br>
                <a href="{% url 'profiles:money_transfer' %}" class="side" id="transfer">Transferência de dinheiro</a> <br> <br>        
                <a href="{% url 'profiles:view_transactions' %}" class="side" id="transfer">Histórico de transferência</a> <br> <br>
            </section>
            {% block bodycontent %}
            {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
        {% block scriptcontent %}
        {% endblock %}
    </body>
</html>

profiles/templates/profiles/view_transactions.html
{% extends 'profiles/profile_base_layout.html' %}
{% load render_table from django_tables2 %}
{% block bodycontent %}
    <h1 style="margin-top: 60px; padding: 10px;">Histórico de Transações</h1>
    <div style="position: absolute; margin-top: 15vh; margin-left: 25vw;">
        {% render_table table %}
    </div>
{% endblock %}

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Trybe Bank</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
            <img src="/static/images/logo-negative-green.svg" width="50px">
            <a class="navbar-brand" href="{% url 'home' %}">&nbsp;Trybe Bank</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="{% url 'home' %}" id="nav-home">Home</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" id="nav-create">Criar conta</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:signin' %}" id="nav-login">Sign In</a>
                    <a class="nav-item nav-link" href="/profile/account_status/">Profile<a>
                    <a class="nav-item nav-link" href="/admin">Admin<a>
                </div>
            </div>
        </nav>

        {% block bodycontent %}

        {% endblock %}
    
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

        {% block scriptcontent %}
        {% endblock %}
        
    </body>
</html>

templates/index.html
{% extends 'base_layout.html' %}

{% block bodycontent %}    
    <div class="container text-center" style="margin-top: 60px; margin-bottom: 20px;">
        <h1>Bem vindo ao Trybe Bank</h1>
    </div>
    <div class="container">
        <a href="{% url 'accounts:signup' %}"><button class="btn btn-primary btn-block" id="acc"><i class="fa fa-user"></i>Criar nova conta</button></a>
        <div style="margin-top: 10px;"></div>
        <a href="{% url 'accounts:signin' %}"><button class="btn btn-danger btn-block" id="sign_in"><i class="fa fa-sign-in"></i> Sign in</button></a>
    </div>
    
    <br>
{% endblock %}